import { cn } from '@/lib/utils';
import type { StreakSnapshot } from '@nthtime/shared';

interface ActivityHeatmapProps {
  snapshot: StreakSnapshot | null;
}

const DAYS = 84;
const COLS = 12;
const ROWS = 7;

function intensityClass(count: number): string {
  if (count <= 0) return 'bg-muted border border-border/60';
  if (count === 1) return 'bg-primary/30';
  if (count === 2) return 'bg-primary/55';
  if (count === 3) return 'bg-primary/75';
  return 'bg-primary';
}

function formatLabel(date: string, count: number): string {
  const unit = count === 1 ? 'pass' : 'passes';
  return `${date} · ${count} ${unit}`;
}

export function ActivityHeatmap({ snapshot }: ActivityHeatmapProps) {
  // Build a stable 84-cell series. Server responses come with 84 entries;
  // anonymous snapshots are generated by computeStreakSnapshot which also
  // returns 84. The fallback keeps the grid rendering if the snapshot is
  // missing entirely (e.g. TanStack Query is still loading).
  const cells =
    snapshot?.heatmap && snapshot.heatmap.length === DAYS
      ? [...snapshot.heatmap]
      : Array.from({ length: DAYS }, () => ({ date: '', count: 0 }));

  return (
    <div className="overflow-x-auto">
      <div
        className="grid"
        style={{
          gridTemplateColumns: `repeat(${COLS}, minmax(0, 1fr))`,
          gridAutoFlow: 'column',
          gridTemplateRows: `repeat(${ROWS}, minmax(0, 1fr))`,
          gap: '0.25rem',
          maxWidth: `${COLS * 16 + (COLS - 1) * 4}px`,
        }}
      >
        {cells.map((cell, index) => (
          <div
            key={cell.date || index}
            style={{ ['--i' as string]: index }}
            className={cn(
              'heatmap-cell h-4 w-4 rounded-[3px] transition-colors',
              intensityClass(cell.count),
            )}
            title={cell.date ? formatLabel(cell.date, cell.count) : undefined}
            aria-label={cell.date ? formatLabel(cell.date, cell.count) : undefined}
          />
        ))}
      </div>
    </div>
  );
}
